language: python

python:
    - "3.6.5"
env:
    - DB=sqlite DJANGO=2.0.6
    - DB=postgresql DJANGO=2.0.6

install:
    - pip install -q Django==$DJANGO pisa reportlab html5lib bs4 psycopg2-binary xlwt xhtml2pdf


before_script:
  - psql -c 'create database report_creator;' -U postgres

script:
    - cd example
    - python manage.py test app --settings=test_project.settings_$DB --noinput

notifications:
  email:
    recipients:
      - joseph@bytcode.com
    on_success: always
    on_failure: always
